### ISSUE TITLE
System.Exception: 'Key 'vc redist 2010' already exists in object.'

### ISSUE THREAD

**Issue by MonkAlex** [shravan2x/Gameloop.Vdf.JsonConverter#2]
Has input info:

```
"4720"
{
	"common"
	{
		"name"		"Condemned: Criminal Origins"
		"languages"
		{
			"english"		"1"
			"german"		"1"
			"french"		"1"
			"italian"		"1"
			"spanish"		"1"
		}
		"clienticon"		"67fd5b51959f48d3459b99996d41c8ea95deedeb"
		"clienttga"		"6cbc6890ec3c4d91937b566b00d6eba028acc597"
		"icon"		"8ea7e69eb0f0f056c39f9c9d655d3885bbe4215a"
		"logo"		"ef7f2aec381356c407801bad681f118fed8e3705"
		"logo_small"		"ef7f2aec381356c407801bad681f118fed8e3705_thumb"
		"type"		"game"
		"metacritic_name"		"Condemned: Criminal Origins"
		"small_capsule"
		{
			"english"		"capsule_231x87.jpg"
		}
		"header_image"
		{
			"english"		"header.jpg"
		}
		"associations"
		{
			"0"
			{
				"type"		"developer"
				"name"		"Monolith"
			}
			"1"
			{
				"type"		"publisher"
				"name"		"SEGA"
			}
		}
		"primary_genre"		"1"
		"genres"
		{
			"0"		"1"
		}
		"category"
		{
			"category_2"		"1"
		}
		"supported_languages"
		{
			"english"
			{
				"supported"		"1"
				"full_audio"		"1"
			}
			"german"
			{
				"supported"		"1"
			}
			"french"
			{
				"supported"		"1"
			}
			"italian"
			{
				"supported"		"1"
			}
			"spanish"
			{
				"supported"		"1"
			}
		}
		"original_release_date"		"1144738800"
		"metacritic_score"		"78"
		"metacritic_fullurl"		"https://www.metacritic.com/game/pc/condemned-criminal-origins?ftag=MCD-06-10aaa1f"
		"community_visible_stats"		"1"
		"community_hub_visible"		"1"
		"gameid"		"4720"
		"store_tags"
		{
			"0"		"1667"
			"1"		"19"
			"2"		"3839"
			"3"		"4166"
			"4"		"3978"
			"5"		"1721"
			"6"		"6378"
			"7"		"4182"
			"8"		"1663"
			"9"		"4026"
			"10"		"4345"
			"11"		"4342"
			"12"		"1693"
			"13"		"5613"
			"14"		"5716"
			"15"		"1662"
			"16"		"1742"
			"17"		"1774"
			"18"		"4064"
			"19"		"4158"
		}
	}
	"extended"
	{
		"developer"		"Monolith"
		"gamedir"		"Condemned: Criminal Origins"
		"homepage"		""
		"icon"		""
		"noservers"		"0"
		"sourcegame"		"1"
		"state"		"eStateAvailable"
		"visibleonlywhensubscribed"		"1"
		"publisher"		"SEGA"
	}
	"config"
	{
		"contenttype"		"3"
		"installdir"		"Condemned Criminal Origins"
		"launch"
		{
			"0"
			{
				"executable"		"Condemned.exe"
				"description"		"Play Game..."
				"config"
				{
					"oslist"		"windows"
				}
			}
			"1"
			{
				"executable"		"Config.exe"
				"description"		"Configure"
				"config"
				{
					"oslist"		"windows"
				}
			}
		}
		"installscriptsignature"		"8f0124c9787fe31d08ef3bec4df66e3cd54b953c05d095f6b60aca5ca9c32e83571c6324592166e4ecddf1e827b63015804ac8b8407d86d2734e86b26c2f4598dc5fea50552c6a315e7aa197e914c266b44bdec218ec8e2ea3900bcea5c89828ec5964257dcd9ef67a6b7664af1f194eec85b628b2bb79b25ab409b7dc30f037"
		"installscriptoverride"		"1"
	}
	"install"
	{
		"run process"
		{
			"directx redist"
			{
				"hasrunkey"		"HKEY_LOCAL_MACHINE\\Software\\Valve\\Steam\\Apps\\4720"
				"process 1"		"%INSTALLDIR%\\Redist\\DirectX\\DXSETUP.exe"
				"command 1"		"/silent"
				"nocleanup"		"1"
			}
			"vc redist 2010"
			{
				"hasrunkey"		"HKEY_LOCAL_MACHINE\\Software\\Valve\\Steam\\Apps\\4720"
				"process 1"		"%INSTALLDIR%\\Redist\\vcredist_x86.exe"
				"command 1"		"/q /norestart"
				"nocleanup"		"1"
				"requirement_os"
				{
					"is64bitwindows"		"0"
				}
			}
			"vc redist 2010"
			{
				"hasrunkey"		"HKEY_LOCAL_MACHINE\\Software\\Valve\\Steam\\Apps\\4720"
				"process 1"		"%INSTALLDIR%\\Redist\\vcredist_x64.exe"
				"command 1"		"/q /norestart"
				"nocleanup"		"1"
				"requirement_os"
				{
					"is64bitwindows"		"1"
				}
			}
		}
	}
	"depots"
	{
		"4721"
		{
			"name"		"Condemned Criminal Origins Content"
			"systemdefined"		"1"
			"config"
			{
				"oslist"		"windows"
			}
			"manifests"
			{
				"public"		"8395113994574511098"
			}
			"maxsize"		"6726114839"
		}
		"4722"
		{
			"name"		"English"
			"config"
			{
				"language"		"english"
				"oslist"		"windows"
			}
			"manifests"
			{
				"public"		"7225834229027005444"
			}
			"maxsize"		"666932"
		}
		"4723"
		{
			"name"		"French"
			"config"
			{
				"language"		"french"
				"oslist"		"windows"
			}
			"manifests"
			{
				"public"		"4147799527871569818"
			}
			"maxsize"		"595960"
		}
		"4724"
		{
			"name"		"German"
			"config"
			{
				"language"		"german"
				"oslist"		"windows"
			}
			"manifests"
			{
				"public"		"8581301575444572156"
			}
			"maxsize"		"596540"
		}
		"4725"
		{
			"name"		"Italian"
			"config"
			{
				"language"		"italian"
				"oslist"		"windows"
			}
			"manifests"
			{
				"public"		"638573850646940651"
			}
			"maxsize"		"570652"
		}
		"4726"
		{
			"name"		"Spanish"
			"config"
			{
				"language"		"spanish"
				"oslist"		"windows"
			}
			"manifests"
			{
				"public"		"4069817558832441280"
			}
			"maxsize"		"570892"
		}
		"overridescddb"		"1"
		"preloadonly"		"1"
		"branches"
		{
			"public"
			{
				"buildid"		"15838"
			}
		}
	}
	"ufs"
	{
		"quota"		"1000000000"
		"maxnumfiles"		"1000"
		"savefiles"
		{
			"0"
			{
				"root"		"WinMyDocuments"
				"path"		"Monolith Productions\\Condemned"
				"pattern"		"*"
				"platforms"
				{
					"1"		"Windows"
				}
				"recursive"		"1"
			}
		}
	}
}
```

When do `VdfConvert.Deserialize(info).ToJson()` get exception
```
System.Exception: Key 'vc redist 2010' already exists in object.
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.HandleObjectDuplicateKey(JObject baseObj, VProperty prop, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VObject obj, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VToken tok, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VProperty prop, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VObject obj, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VToken tok, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VProperty prop, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VObject obj, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VToken tok, VdfJsonConversionSettings settings)
   at Gameloop.Vdf.JsonConverter.VTokenExtensions.ToJson(VProperty prop, VdfJsonConversionSettings settings)
```

**Comment by shravan2x** [comment]
The exception is thrown since the key "vc redist 2010" exists twice in your data. `VdfJsonConversionSettings` has an `ObjectDuplicateKeyHandling` setting that you can use to handle the duplicate object key as you like. For example, you could change your code to:
```
VdfConvert.Deserialize(info).ToJson(new VdfJsonConversionSettings { ObjectDuplicateKeyHandling = DuplicateKeyHandling.Ignore });
```

However, in your case, it appears that you need _both_ the objects since they have different values for `is64bitwindows`. The `ObjectDuplicateKeyHandling` settings only allows you to:
1. Ignore duplicate objects entirely (i.e. only the first is used)
2. Update old objects with new ones (i.e. only the last is used) or
3. Merge all duplicate objects by their key

If you need both values, you have to process the VDF data as a `VObject` before you try to convert it to JSON.

**Comment by MonkAlex** [comment]
@shravan2x 
its valid steam-app data, ignore or update objects lost info.
maybe some hack to convert `run process` node to not unique collection?
maybe i need just rename duplicate in VDF, but VDF valid in this case :(

PS: i has another VDFs with this exception, not analized what data duplicate.

**Comment by shravan2x** [comment]
> its valid steam-app data, ignore or update objects lost info.

I'm aware that many legitimate VDF have duplicate keys, but the JSON format simply does not allow them.

> maybe some hack to convert run process node to not unique collection?
maybe i need just rename duplicate in VDF, but VDF valid in this case :(

No, you can just update the `VObject` before you convert it. For example:
```c#
VProperty prop = VdfConvert.Deserialize(info);
VObject obj = prop.Value.Value<VObject>("install").Value<VObject>("run process");

int counter = 0;
foreach (VProperty child in obj.Children().Where(x => x.Key == "vc redist 2010"))
    child.Key = $"vc redist 2010 [{counter++}]";
Console.WriteLine(prop.ToJson());
```

This code will result in this JSON:
```json
// ... rest of the json
"run process": {
  "directx redist": {
    "hasrunkey": "HKEY_LOCAL_MACHINE\\Software\\Valve\\Steam\\Apps\\4720",
    "process 1": "%INSTALLDIR%\\Redist\\DirectX\\DXSETUP.exe",
    "command 1": "/silent",
    "nocleanup": "1"
  },
  "vc redist 2010 [0]": {
    "hasrunkey": "HKEY_LOCAL_MACHINE\\Software\\Valve\\Steam\\Apps\\4720",
    "process 1": "%INSTALLDIR%\\Redist\\vcredist_x86.exe",
    "command 1": "/q /norestart",
    "nocleanup": "1",
    "requirement_os": {
      "is64bitwindows": "0"
    }
  },
  "vc redist 2010 [1]": {
    "hasrunkey": "HKEY_LOCAL_MACHINE\\Software\\Valve\\Steam\\Apps\\4720",
    "process 1": "%INSTALLDIR%\\Redist\\vcredist_x64.exe",
    "command 1": "/q /norestart",
    "nocleanup": "1",
    "requirement_os": {
      "is64bitwindows": "1"
    }
  }
}
// ... rest of the json
```

Keep in mind that if you ever want to reconstruct the original VDF, you'll have to reverse this conversion process.

> PS: i has another VDFs with this exception, not analized what data duplicate.

You'll have to use code similar to the above, but with keys changed.

**Comment by shravan2x** [comment]
Closing due to inactivity. Feel free to reopen if you still need help.
